### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mml1** [MoonBaseTom/teacozy#4]
(Exceeds Expectations) You have great naming conventions, comments, and well organized code. Keep it up! Your future self and coworkers will thank you. The only suggestion for improvement I have is for you to keep the DRY principle in mind and see if there is anywhere you are repeating code. If there is, ask yourself if you can simplify the code, in this case your CSS styles. 

As a further challenge, consider adding mobile resizing or responsive design. This will take some extra research, but based on your work here, I think it’s a challenge you’re ready for.

**Comment by TechnicallyThomas** [comment]
Thank you so much for your input! :)
